# Generated by Django 5.0.3 on 2024-03-28 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CallDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('callee', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CDR.caller')),
            ],
        ),
    ]
